### ISSUE TITLE
`mean`'s dry run

### ISSUE THREAD

**Issue by thevolatilebit** [JuliaStats/Statistics.jl#124]
I used to assume that `mean(f, itr)` calls `f` once for each of the elements of `itr`.

However, there is an (extra) dry run which 

- may lead to unwanted behaviour for `f`s that mutate the state,
- may negatively influence the overall performance (my primary motivation).

In Slack's #helpdesk channel, it was also noted that there could be some issues with weirdly indexed arrays.

For example, 
```
g3 = 0; mean(i -> (global g3 += 1; 1), 1:1)
```
results in `g3 == 2`.

Moreover, this behaviour is _not_ documented.

**Comment by fredrikekre** [comment]
See #49

**Comment by thevolatilebit** [comment]
Right, closing as duplicate.
